apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crud-chart.fullname" . }}-config
data:
  dbHost: {{ .Release.Name }}-postgresql
  dbPort: {{ .Values.postgresql.containerPorts.postgresql | quote }}