apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
    {{- include "crud-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crud-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crud-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: dbName
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-config
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-config
                  key: dbPort
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
