apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crud-chart.fullname" . }}-secret
type: Opaque
data:
  dbUsername: {{.Values.postgresql.auth.username|b64enc}}
  dbPassword: {{.Values.postgresql.auth.password|b64enc}}
  dbName: {{.Values.postgresql.auth.database|b64enc}}