{
 "title": "User CRUD application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (max quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by(le, method) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_server_requests_seconds_count{uri=~\"/api/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate (Internal Server Error: 500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_server_requests_seconds_count{uri=~\"/api/.*\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, method) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, method) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, method) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (max quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, \n      sum by (le, method) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_requests[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate (Internal Server Error: 500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PODs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"hw-5-crud-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"hw-5-crud-.*\"}) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}